CREATE TABLE IF NOT EXISTS mpa (
                                   mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name   VARCHAR(10) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS genres (
                                      genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name     VARCHAR(100) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS users (
                                     user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255),
    birthday DATE
    );

CREATE TABLE IF NOT EXISTS films (
                                     film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name         VARCHAR(255) NOT NULL,
    description  VARCHAR(200),
    release_date DATE NOT NULL,
    duration     INTEGER NOT NULL CHECK (duration > 0),
    mpa_id       INTEGER NOT NULL,
    CONSTRAINT fk_films_mpa FOREIGN KEY (mpa_id) REFERENCES mpa (mpa_id)
    );

CREATE TABLE IF NOT EXISTS film_genres (
                                           film_id  INTEGER NOT NULL,
                                           genre_id INTEGER NOT NULL,
                                           CONSTRAINT pk_film_genres PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_film_genres_film FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
    CONSTRAINT fk_film_genres_genre FOREIGN KEY (genre_id) REFERENCES genres (genre_id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS likes (
                                     film_id INTEGER NOT NULL,
                                     user_id INTEGER NOT NULL,
                                     CONSTRAINT pk_likes PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_likes_film FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
    CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS friendship (
                                          user_id   INTEGER NOT NULL,
                                          friend_id INTEGER NOT NULL,
                                          status    VARCHAR(20) NOT NULL CHECK (status IN ('UNCONFIRMED', 'CONFIRMED')),
    CONSTRAINT pk_friendship PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friendship_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_friendship_friend FOREIGN KEY (friend_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT chk_friendship_not_self CHECK (user_id <> friend_id)
    );